### PR TITLE
Add CI via GitHub Actions

### PR DESCRIPTION
**Pull request by jrr**
This PR configures [GitHub Actions](https://help.github.com/en/actions) to build on Linux and Windows with every commit. Highlights:

- Here's an example of a successful run:

   https://github.com/jrr/Freestyle-Edge-Pro-SmartSet-App/actions/runs/55956548

- Each build saves its artifacts so you can easily download the latest executable.
- There's one small code change to `Common/u_const.pas` to fix the Linux build.
- I threw together a Makefile to handle component dependencies. I've never used Pascal or Lazarus before; I'd be glad to hear if there's a better way to build the whole project at once.

I have a Mac build running on a [branch](https://github.com/jrr/Freestyle-Edge-Pro-SmartSet-App/tree/feature/mac-ci), but it's failing with a couple [errors](https://github.com/jrr/Freestyle-Edge-Pro-SmartSet-App/runs/509173548?check_suite_focus=true). Is the latest Mac-specific work pushed up to this repo?

### CODE REVIEW

**Comment by jrr** [comment]
@KinesisCorporation any feedback?

**Comment by KinesisCorporation** [comment]
Hello @jrr,

We will have an updated repo coming this week containing all our different SmartSet apps including instructions on how to install and configure Lazarus and also build instructions for Windows and MacOS.

Will keep you updated here.

Thanks for your implication!

**Comment by jrr** [comment]
@KinesisCorporation any update on the new repo?

**Comment by KinesisCorporation** [comment]
@jrr source has been moved here as of today: https://github.com/KinesisCorporation/SmartSetApps

**Comment by jrr** [comment]
The new repo looks good! I'll close this PR and try to do something similar over there.

**Comment by jrr** [comment]
For anyone that was following this issue, here's the sequel: https://github.com/KinesisCorporation/SmartSetApps/pull/1

**Pull request closed without merging**
